"""
Revision ID: 0670a7abef8b
Revises: 452b5296a164
Create Date: 2025-05-01 07:33:14.031831

"""

# revision identifiers, used by Alembic.
revision = '0670a7abef8b'
down_revision = '452b5296a164'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itinerary_lol',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itinerary_lol')
    # ### end Alembic commands ###
