"""
Revision ID: 4389e7d195b3
Revises: 0670a7abef8b
Create Date: 2025-05-01 07:33:39.674773

"""

# revision identifiers, used by Alembic.
revision = '4389e7d195b3'
down_revision = '0670a7abef8b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itinerary_lol')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itinerary_lol',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='itinerary_lol_pkey')
    )
    # ### end Alembic commands ###
