"""
Revision ID: 452b5296a164
Revises: c6223a9acfc1
Create Date: 2025-05-01 07:26:36.365257

"""

# revision identifiers, used by Alembic.
revision = '452b5296a164'
down_revision = 'c6223a9acfc1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
