"""d

Revision ID: 461f1bdf261c
Revises: 6f9670821d14
Create Date: 2025-05-01 15:48:59.349869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '461f1bdf261c'
down_revision: Union[str, None] = '6f9670821d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day_transfers', sa.Column('template', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('day_transfers', 'template')
    # ### end Alembic commands ###