"""u1

Revision ID: 6f9670821d14
Revises: d66fada6f8cc
Create Date: 2025-05-01 15:47:29.847440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f9670821d14'
down_revision: Union[str, None] = 'd66fada6f8cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day_activities', sa.Column('template', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('day_activities', 'template')
    # ### end Alembic commands ###
