"""
Revision ID: 84743518e58c
Revises: 461f1bdf261c
Create Date: 2025-05-01 16:52:16.324474

"""

# revision identifiers, used by Alembic.
revision = '84743518e58c'
down_revision = '461f1bdf261c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('duration', sa.Float(), nullable=True))
    op.add_column('templates', sa.Column('destinations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'destinations')
    op.drop_column('activities', 'duration')
    # ### end Alembic commands ###
