"""
Revision ID: c6223a9acfc1
Revises: 
Create Date: 2025-05-01 07:24:49.563817

"""

# revision identifiers, used by Alembic.
revision = 'c6223a9acfc1'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_destinations_is_active'), 'destinations', ['is_active'], unique=False)
    op.create_table('itineraries',
    sa.Column('organisation_id', sa.UUID(), nullable=True),
    sa.Column('traveler_name', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('nights', sa.Integer(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itineraries_is_active'), 'itineraries', ['is_active'], unique=False)
    op.create_index(op.f('ix_itineraries_organisation_id'), 'itineraries', ['organisation_id'], unique=False)
    op.create_table('templates',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nights', sa.Integer(), nullable=False),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('budget', sa.String(), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('avg_cost', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_templates_budget'), 'templates', ['budget'], unique=False)
    op.create_index(op.f('ix_templates_is_active'), 'templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_templates_nights'), 'templates', ['nights'], unique=False)
    op.create_index(op.f('ix_templates_style'), 'templates', ['style'], unique=False)
    op.create_table('transport_modes',
    sa.Column('code', sa.Enum('FLIGHT', 'FERRY', 'BUS', 'TAXI', 'PRIVATE_CAR', 'MINIVAN', name='transportmodeenum'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_transport_modes_is_active'), 'transport_modes', ['is_active'], unique=False)
    op.create_table('itinerary_days',
    sa.Column('itinerary_id', sa.UUID(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('itinerary_id', 'day_number', name='uq_itinerary_day_number')
    )
    op.create_index('ix_itinerary_day_itinerary_date', 'itinerary_days', ['itinerary_id', 'date'], unique=False)
    op.create_index(op.f('ix_itinerary_days_is_active'), 'itinerary_days', ['is_active'], unique=False)
    op.create_index(op.f('ix_itinerary_days_itinerary_id'), 'itinerary_days', ['itinerary_id'], unique=False)
    op.create_table('locations',
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_destination_id'), 'locations', ['destination_id'], unique=False)
    op.create_index(op.f('ix_locations_is_active'), 'locations', ['is_active'], unique=False)
    op.create_table('activities',
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('price_min', sa.Float(), nullable=True),
    sa.Column('price_max', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_is_active'), 'activities', ['is_active'], unique=False)
    op.create_index(op.f('ix_activities_location_id'), 'activities', ['location_id'], unique=False)
    op.create_table('day_transfers',
    sa.Column('itinerary_day_id', sa.UUID(), nullable=False),
    sa.Column('mode_id', sa.UUID(), nullable=False),
    sa.Column('from_location_id', sa.UUID(), nullable=False),
    sa.Column('to_location_id', sa.UUID(), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['itinerary_day_id'], ['itinerary_days.id'], ),
    sa.ForeignKeyConstraint(['mode_id'], ['transport_modes.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_day_transfers_from_location_id'), 'day_transfers', ['from_location_id'], unique=False)
    op.create_index(op.f('ix_day_transfers_is_active'), 'day_transfers', ['is_active'], unique=False)
    op.create_index(op.f('ix_day_transfers_itinerary_day_id'), 'day_transfers', ['itinerary_day_id'], unique=False)
    op.create_index(op.f('ix_day_transfers_mode_id'), 'day_transfers', ['mode_id'], unique=False)
    op.create_index(op.f('ix_day_transfers_to_location_id'), 'day_transfers', ['to_location_id'], unique=False)
    op.create_table('hotels',
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amenities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotels_is_active'), 'hotels', ['is_active'], unique=False)
    op.create_index(op.f('ix_hotels_location_id'), 'hotels', ['location_id'], unique=False)
    op.create_table('day_activities',
    sa.Column('itinerary_day_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('timeslot', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['itinerary_day_id'], ['itinerary_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_day_activities_activity_id'), 'day_activities', ['activity_id'], unique=False)
    op.create_index(op.f('ix_day_activities_is_active'), 'day_activities', ['is_active'], unique=False)
    op.create_index(op.f('ix_day_activities_itinerary_day_id'), 'day_activities', ['itinerary_day_id'], unique=False)
    op.create_table('day_hotels',
    sa.Column('itinerary_day_id', sa.UUID(), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('check_in_time', sa.Time(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.ForeignKeyConstraint(['itinerary_day_id'], ['itinerary_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_day_hotels_hotel_id'), 'day_hotels', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_day_hotels_is_active'), 'day_hotels', ['is_active'], unique=False)
    op.create_index(op.f('ix_day_hotels_itinerary_day_id'), 'day_hotels', ['itinerary_day_id'], unique=True)
    op.create_table('template_days',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('day_offset', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=True),
    sa.Column('activity_id', sa.UUID(), nullable=True),
    sa.Column('transfer_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['transport_modes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_days_activity_id'), 'template_days', ['activity_id'], unique=False)
    op.create_index(op.f('ix_template_days_hotel_id'), 'template_days', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_template_days_is_active'), 'template_days', ['is_active'], unique=False)
    op.create_index(op.f('ix_template_days_template_id'), 'template_days', ['template_id'], unique=False)
    op.create_index(op.f('ix_template_days_transfer_id'), 'template_days', ['transfer_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_days_transfer_id'), table_name='template_days')
    op.drop_index(op.f('ix_template_days_template_id'), table_name='template_days')
    op.drop_index(op.f('ix_template_days_is_active'), table_name='template_days')
    op.drop_index(op.f('ix_template_days_hotel_id'), table_name='template_days')
    op.drop_index(op.f('ix_template_days_activity_id'), table_name='template_days')
    op.drop_table('template_days')
    op.drop_index(op.f('ix_day_hotels_itinerary_day_id'), table_name='day_hotels')
    op.drop_index(op.f('ix_day_hotels_is_active'), table_name='day_hotels')
    op.drop_index(op.f('ix_day_hotels_hotel_id'), table_name='day_hotels')
    op.drop_table('day_hotels')
    op.drop_index(op.f('ix_day_activities_itinerary_day_id'), table_name='day_activities')
    op.drop_index(op.f('ix_day_activities_is_active'), table_name='day_activities')
    op.drop_index(op.f('ix_day_activities_activity_id'), table_name='day_activities')
    op.drop_table('day_activities')
    op.drop_index(op.f('ix_hotels_location_id'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_is_active'), table_name='hotels')
    op.drop_table('hotels')
    op.drop_index(op.f('ix_day_transfers_to_location_id'), table_name='day_transfers')
    op.drop_index(op.f('ix_day_transfers_mode_id'), table_name='day_transfers')
    op.drop_index(op.f('ix_day_transfers_itinerary_day_id'), table_name='day_transfers')
    op.drop_index(op.f('ix_day_transfers_is_active'), table_name='day_transfers')
    op.drop_index(op.f('ix_day_transfers_from_location_id'), table_name='day_transfers')
    op.drop_table('day_transfers')
    op.drop_index(op.f('ix_activities_location_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_is_active'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_locations_is_active'), table_name='locations')
    op.drop_index(op.f('ix_locations_destination_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_itinerary_days_itinerary_id'), table_name='itinerary_days')
    op.drop_index(op.f('ix_itinerary_days_is_active'), table_name='itinerary_days')
    op.drop_index('ix_itinerary_day_itinerary_date', table_name='itinerary_days')
    op.drop_table('itinerary_days')
    op.drop_index(op.f('ix_transport_modes_is_active'), table_name='transport_modes')
    op.drop_table('transport_modes')
    op.drop_index(op.f('ix_templates_style'), table_name='templates')
    op.drop_index(op.f('ix_templates_nights'), table_name='templates')
    op.drop_index(op.f('ix_templates_is_active'), table_name='templates')
    op.drop_index(op.f('ix_templates_budget'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_itineraries_organisation_id'), table_name='itineraries')
    op.drop_index(op.f('ix_itineraries_is_active'), table_name='itineraries')
    op.drop_table('itineraries')
    op.drop_index(op.f('ix_destinations_is_active'), table_name='destinations')
    op.drop_table('destinations')
    # ### end Alembic commands ###
