"""
Revision ID: d66fada6f8cc
Revises: 4389e7d195b3
Create Date: 2025-05-01 10:22:05.122985

"""

# revision identifiers, used by Alembic.
revision = 'd66fada6f8cc'
down_revision = '4389e7d195b3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itinerary_days', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itinerary_days', 'notes')
    # ### end Alembic commands ###
