"""
Revision ID: e555fc0a3908
Revises: 84743518e58c
Create Date: 2025-05-01 16:57:45.236700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e555fc0a3908'
down_revision: Union[str, None] = '84743518e58c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('activities', 'duration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_activities_category'), 'activities', ['category'], unique=False)
    op.add_column('day_activities', sa.Column('template', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('day_hotels', sa.Column('template', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('day_transfers', sa.Column('template', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('day_transfers', 'template')
    op.drop_column('day_hotels', 'template')
    op.drop_column('day_activities', 'template')
    op.drop_index(op.f('ix_activities_category'), table_name='activities')
    op.alter_column('activities', 'duration',
               existing_type=sa.String(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('activities', 'description')
    # ### end Alembic commands ###
